/**
 * Blindados 16 tiros – 25 carros blindados (vehicles.lua).
 * Imagens: assets/vehicles/{model}.png
 */
window.BLINDADOS_16_TIROS = [
    { model: 'baller5', nome: 'Baller LE (Armored)', brand: 'Gallivanter', preco: 140, descricao: 'SUV blindado Gallivanter. Resistência a 16 tiros. Entrega na garagem após o pagamento.', beneficios: ['Blindado 16 tiros', 'Entrega na garagem', 'Permanente'], dadosTecnicos: ['Modelo: baller5', 'Categoria: SUVs', 'Tipo: automobile', 'Blindagem: 16 tiros', 'Slots do baú: 35', 'Peso máx. baú: 50 kg', 'Entrega: garagem'] },
    { model: 'baller6', nome: 'Baller LE LWB (Armored)', brand: 'Gallivanter', preco: 150, descricao: 'SUV blindado Gallivanter versão longa. Resistência a 16 tiros. Entrega na garagem.', beneficios: ['Blindado 16 tiros', 'Entrega na garagem', 'Permanente'], dadosTecnicos: ['Modelo: baller6', 'Categoria: SUVs', 'Tipo: automobile', 'Blindagem: 16 tiros', 'Slots do baú: 35', 'Peso máx. baú: 50 kg', 'Entrega: garagem'] },
    { model: 'schafter5', nome: 'Schafter 5', brand: 'Benefactor', preco: 130, descricao: 'Sedan blindado Benefactor. Resistência a 16 tiros. Entrega na garagem.', beneficios: ['Blindado 16 tiros', 'Entrega na garagem', 'Permanente'], dadosTecnicos: ['Modelo: schafter5', 'Categoria: sedans', 'Tipo: automobile', 'Blindagem: 16 tiros', 'Slots do baú: 35', 'Peso máx. baú: 50 kg', 'Entrega: garagem'] },
    { model: 'xls2', nome: 'XLS 2', brand: 'Benefactor', preco: 125, descricao: 'SUV blindado Benefactor. Resistência a 16 tiros. Entrega na garagem.', beneficios: ['Blindado 16 tiros', 'Entrega na garagem', 'Permanente'], dadosTecnicos: ['Modelo: xls2', 'Categoria: SUVs', 'Tipo: automobile', 'Blindagem: 16 tiros', 'Slots do baú: 35', 'Peso máx. baú: 50 kg', 'Entrega: garagem'] },
    { model: 'kuruma2', nome: 'Kuruma Armored', brand: 'Karin', preco: 145, descricao: 'Sedan blindado Karin. Resistência a 16 tiros. Entrega na garagem.', beneficios: ['Blindado 16 tiros', 'Entrega na garagem', 'Permanente'], dadosTecnicos: ['Modelo: kuruma2', 'Categoria: sports', 'Tipo: automobile', 'Blindagem: 16 tiros', 'Slots do baú: 30', 'Peso máx. baú: 40 kg', 'Entrega: garagem'] },
    { model: 'wrarmoredg63', nome: 'G63 Blindado', brand: 'Mantem', preco: 180, descricao: 'SUV blindado Mantem. Resistência a 16 tiros. Entrega na garagem.', beneficios: ['Blindado 16 tiros', 'Entrega na garagem', 'Permanente'], dadosTecnicos: ['Modelo: wrarmoredg63', 'Categoria: super', 'Tipo: automobile', 'Blindagem: 16 tiros', 'Slots do baú: 40', 'Peso máx. baú: 65 kg', 'Entrega: garagem'] },
    { model: 'wrarmoredconada', nome: 'Conada Blindado', brand: 'Mantem', preco: 180, descricao: 'Veículo blindado Mantem. Resistência a 16 tiros. Entrega na garagem.', beneficios: ['Blindado 16 tiros', 'Entrega na garagem', 'Permanente'], dadosTecnicos: ['Modelo: wrarmoredconada', 'Categoria: super', 'Tipo: automobile', 'Blindagem: 16 tiros', 'Slots do baú: 25', 'Peso máx. baú: 35 kg', 'Entrega: garagem'] },
    { model: 'wrarmoredurus', nome: 'Urus Blindada', brand: 'Mantem', preco: 185, descricao: 'SUV blindada Mantem. Resistência a 16 tiros. Entrega na garagem.', beneficios: ['Blindado 16 tiros', 'Entrega na garagem', 'Permanente'], dadosTecnicos: ['Modelo: wrarmoredurus', 'Categoria: super', 'Tipo: automobile', 'Blindagem: 16 tiros', 'Slots do baú: 40', 'Peso máx. baú: 60 kg', 'Entrega: garagem'] },
    { model: 'wrarmoredct', nome: 'CT Blindado', brand: 'Mantem', preco: 175, descricao: 'Carro blindado Mantem. Resistência a 16 tiros. Entrega na garagem.', beneficios: ['Blindado 16 tiros', 'Entrega na garagem', 'Permanente'], dadosTecnicos: ['Modelo: wrarmoredct', 'Categoria: super', 'Tipo: automobile', 'Blindagem: 16 tiros', 'Slots do baú: 35', 'Peso máx. baú: 45 kg', 'Entrega: garagem'] },
    { model: 'wrarmoredcayenne', nome: 'Cayenne GT Blindado', brand: 'Mantem', preco: 195, descricao: 'SUV blindado Mantem. Resistência a 16 tiros. Entrega na garagem.', beneficios: ['Blindado 16 tiros', 'Entrega na garagem', 'Permanente'], dadosTecnicos: ['Modelo: wrarmoredcayenne', 'Categoria: super', 'Tipo: automobile', 'Blindagem: 16 tiros', 'Slots do baú: 40', 'Peso máx. baú: 65 kg', 'Entrega: garagem'] },
    { model: 'wrarmoredgle', nome: 'GLE63 Blindado', brand: 'Mantem', preco: 190, descricao: 'SUV blindado Mantem. Resistência a 16 tiros. Entrega na garagem.', beneficios: ['Blindado 16 tiros', 'Entrega na garagem', 'Permanente'], dadosTecnicos: ['Modelo: wrarmoredgle', 'Categoria: super', 'Tipo: automobile', 'Blindagem: 16 tiros', 'Slots do baú: 40', 'Peso máx. baú: 65 kg', 'Entrega: garagem'] },
    { model: 'wrarmoredjettagli', nome: 'Jetta GLI Blindado', brand: 'Mantem', preco: 170, descricao: 'Sedan blindado Mantem. Resistência a 16 tiros. Entrega na garagem.', beneficios: ['Blindado 16 tiros', 'Entrega na garagem', 'Permanente'], dadosTecnicos: ['Modelo: wrarmoredjettagli', 'Categoria: super', 'Tipo: automobile', 'Blindagem: 16 tiros', 'Slots do baú: 35', 'Peso máx. baú: 50 kg', 'Entrega: garagem'] },
    { model: 'wrarmoredm3g80c', nome: 'M3 G80C Blindado', brand: 'Mantem', preco: 195, descricao: 'Sedan blindado Mantem. Resistência a 16 tiros. Entrega na garagem.', beneficios: ['Blindado 16 tiros', 'Entrega na garagem', 'Permanente'], dadosTecnicos: ['Modelo: wrarmoredm3g80c', 'Categoria: super', 'Tipo: automobile', 'Blindagem: 16 tiros', 'Slots do baú: 35', 'Peso máx. baú: 45 kg', 'Entrega: garagem'] },
    { model: 'wrarmoredm5', nome: 'M5 SL Blindado', brand: 'Mantem', preco: 195, descricao: 'Sedan blindado Mantem. Resistência a 16 tiros. Entrega na garagem.', beneficios: ['Blindado 16 tiros', 'Entrega na garagem', 'Permanente'], dadosTecnicos: ['Modelo: wrarmoredm5', 'Categoria: super', 'Tipo: automobile', 'Blindagem: 16 tiros', 'Slots do baú: 35', 'Peso máx. baú: 50 kg', 'Entrega: garagem'] },
    { model: 'wrarmoredmacan', nome: 'Macan Blindado', brand: 'Mantem', preco: 185, descricao: 'SUV blindado Mantem. Resistência a 16 tiros. Entrega na garagem.', beneficios: ['Blindado 16 tiros', 'Entrega na garagem', 'Permanente'], dadosTecnicos: ['Modelo: wrarmoredmacan', 'Categoria: super', 'Tipo: automobile', 'Blindagem: 16 tiros', 'Slots do baú: 35', 'Peso máx. baú: 55 kg', 'Entrega: garagem'] },
    { model: 'wrarmoredrs7', nome: 'RS7 Blindado', brand: 'Mantem', preco: 195, descricao: 'Sedan blindado Mantem. Resistência a 16 tiros. Entrega na garagem.', beneficios: ['Blindado 16 tiros', 'Entrega na garagem', 'Permanente'], dadosTecnicos: ['Modelo: wrarmoredrs7', 'Categoria: super', 'Tipo: automobile', 'Blindagem: 16 tiros', 'Slots do baú: 35', 'Peso máx. baú: 50 kg', 'Entrega: garagem'] },
    { model: 'wrarmoredvelar', nome: 'Velar Blindado', brand: 'Mantem', preco: 190, descricao: 'SUV blindado Mantem. Resistência a 16 tiros. Entrega na garagem.', beneficios: ['Blindado 16 tiros', 'Entrega na garagem', 'Permanente'], dadosTecnicos: ['Modelo: wrarmoredvelar', 'Categoria: super', 'Tipo: automobile', 'Blindagem: 16 tiros', 'Slots do baú: 40', 'Peso máx. baú: 60 kg', 'Entrega: garagem'] },
    { model: 'wrarmoredx7m60i', nome: 'X7 M60i Blindado', brand: 'Mantem', preco: 200, descricao: 'SUV blindado Mantem. Resistência a 16 tiros. Entrega na garagem.', beneficios: ['Blindado 16 tiros', 'Entrega na garagem', 'Permanente'], dadosTecnicos: ['Modelo: wrarmoredx7m60i', 'Categoria: super', 'Tipo: automobile', 'Blindagem: 16 tiros', 'Slots do baú: 45', 'Peso máx. baú: 75 kg', 'Entrega: garagem'] },
    { model: 'wrarmoredx6', nome: 'X6 F96 Blindado', brand: 'Mantem', preco: 195, descricao: 'SUV blindado Mantem. Resistência a 16 tiros. Entrega na garagem.', beneficios: ['Blindado 16 tiros', 'Entrega na garagem', 'Permanente'], dadosTecnicos: ['Modelo: wrarmoredx6', 'Categoria: super', 'Tipo: automobile', 'Blindagem: 16 tiros', 'Slots do baú: 40', 'Peso máx. baú: 65 kg', 'Entrega: garagem'] },
    { model: 'armored18velar', nome: 'Velar Blindada', brand: 'Mantem', preco: 185, descricao: 'SUV blindada Mantem. Resistência a 16 tiros. Entrega na garagem.', beneficios: ['Blindado 16 tiros', 'Entrega na garagem', 'Permanente'], dadosTecnicos: ['Modelo: armored18velar', 'Categoria: super', 'Tipo: automobile', 'Blindagem: 16 tiros', 'Slots do baú: 40', 'Peso máx. baú: 60 kg', 'Entrega: garagem'] },
    { model: 'armoredx7m60i', nome: 'X7 2024 Blindada', brand: 'Mantem', preco: 195, descricao: 'SUV blindada Mantem. Resistência a 16 tiros. Entrega na garagem.', beneficios: ['Blindado 16 tiros', 'Entrega na garagem', 'Permanente'], dadosTecnicos: ['Modelo: armoredx7m60i', 'Categoria: super', 'Tipo: automobile', 'Blindagem: 16 tiros', 'Slots do baú: 45', 'Peso máx. baú: 75 kg', 'Entrega: garagem'] },
    { model: 'wrarmoredgls600', nome: 'GLS 600 Blindado', brand: 'Mantem', preco: 195, descricao: 'SUV blindado Mantem. Resistência a 16 tiros. Entrega na garagem.', beneficios: ['Blindado 16 tiros', 'Entrega na garagem', 'Permanente'], dadosTecnicos: ['Modelo: wrarmoredgls600', 'Categoria: super', 'Tipo: automobile', 'Blindagem: 16 tiros', 'Slots do baú: 45', 'Peso máx. baú: 80 kg', 'Entrega: garagem'] },
    { model: 'wrarmoredpurosangue', nome: 'Purosangue Blindado', brand: 'Mantem', preco: 200, descricao: 'SUV blindado Mantem. Resistência a 16 tiros. Entrega na garagem.', beneficios: ['Blindado 16 tiros', 'Entrega na garagem', 'Permanente'], dadosTecnicos: ['Modelo: wrarmoredpurosangue', 'Categoria: super', 'Tipo: automobile', 'Blindagem: 16 tiros', 'Slots do baú: 40', 'Peso máx. baú: 60 kg', 'Entrega: garagem'] },
    { model: 'wrarmoredvenatus', nome: 'Venatus Blindado', brand: 'Mantem', preco: 195, descricao: 'Carro blindado Mantem. Resistência a 16 tiros. Entrega na garagem.', beneficios: ['Blindado 16 tiros', 'Entrega na garagem', 'Permanente'], dadosTecnicos: ['Modelo: wrarmoredvenatus', 'Categoria: super', 'Tipo: automobile', 'Blindagem: 16 tiros', 'Slots do baú: 35', 'Peso máx. baú: 45 kg', 'Entrega: garagem'] },
    { model: 'wrarmoredescalade', nome: 'Armored Escalade', brand: 'Mantem', preco: 190, descricao: 'SUV blindado Mantem. Resistência a 16 tiros. Entrega na garagem.', beneficios: ['Blindado 16 tiros', 'Entrega na garagem', 'Permanente'], dadosTecnicos: ['Modelo: wrarmoredescalade', 'Categoria: super', 'Tipo: automobile', 'Blindagem: 16 tiros', 'Slots do baú: 45', 'Peso máx. baú: 80 kg', 'Entrega: garagem'] }
];

/** Blindados 16 tiros COM PNEU FULL – mesmos 25 carros, com pneus blindados (não estouram). Entrega igual Santa. */
window.BLINDADOS_16_TIROS_PNEU_FULL = (function () {
    var list = window.BLINDADOS_16_TIROS;
    if (!list) return [];
    return list.map(function (v) {
        return {
            model: v.model,
            nome: v.nome,
            brand: v.brand,
            preco: (v.preco || 0) + 15,
            imageFolder: 'vehicles',
            descricao: (v.descricao || '').replace('16 tiros.', '16 tiros com pneus full (não estouram).') || 'Blindado 16 tiros com pneus full. Entrega na garagem.',
            beneficios: ['Blindado 16 tiros', 'Pneus full (não estouram)', 'Entrega na garagem', 'Permanente'],
            dadosTecnicos: (v.dadosTecnicos || []).concat(['Pneus: full (bulletproof)'])
        };
    });
})();

(function () {
    var list = window.BLINDADOS_16_TIROS;
    if (!list) return;
    list.forEach(function (v) {
        v.imageFolder = 'vehicles';
    });
})();

/**
 * Blindados 32 tiros – veículos de ALTA RESISTÊNCIA (base: especial/ficha – Nightshark, Insurgent, Menacer, etc.).
 * Diferente dos 25 carros 16 tiros. productId: blindado_32_<model>
 */
window.BLINDADOS_32_TIROS = [
    { model: 'nightshark', nome: 'Nightshark', brand: 'HVY', preco: 230, imageFolder: 'vehicles', descricao: 'SUV blindado (HVY) com metralhadoras duplas. Muito resistente a explosões e tiros. Resistência a 32 tiros.', beneficios: ['Blindado 32 tiros', 'Metralhadoras duplas', 'Entrega na garagem', 'Permanente'], dadosTecnicos: ['Modelo: nightshark', 'Categoria: Off-road', 'Blindagem: 32 tiros', 'Slots do baú: 35', 'Peso máx. baú: 180 kg', 'Entrega: garagem'] },
    { model: 'insurgent', nome: 'Insurgent Pick-Up', brand: 'HVY', preco: 260, imageFolder: 'vehicles', descricao: 'Pick-up blindado. Alta resistência a 32 tiros; metralhadora .50 opcional na caçamba.', beneficios: ['Blindado 32 tiros', 'Metralhadora opcional', 'Entrega na garagem', 'Permanente'], dadosTecnicos: ['Modelo: insurgent', 'Categoria: Off-road', 'Blindagem: 32 tiros', 'Slots do baú: 35', 'Peso máx. baú: 180 kg', 'Entrega: garagem'] },
    { model: 'insurgent2', nome: 'Insurgent', brand: 'HVY', preco: 260, imageFolder: 'vehicles', descricao: 'SUV blindado HVY. Alta resistência a 32 tiros.', beneficios: ['Blindado 32 tiros', 'Entrega na garagem', 'Permanente'], dadosTecnicos: ['Modelo: insurgent2', 'Categoria: Off-road', 'Blindagem: 32 tiros', 'Slots do baú: 35', 'Peso máx. baú: 180 kg', 'Entrega: garagem'] },
    { model: 'insurgent3', nome: 'Insurgent Custom', brand: 'HVY', preco: 270, imageFolder: 'vehicles', descricao: 'Insurgent customizado. Blindagem 32 tiros e metralhadora na caçamba.', beneficios: ['Blindado 32 tiros', 'Metralhadora caçamba', 'Entrega na garagem', 'Permanente'], dadosTecnicos: ['Modelo: insurgent3', 'Categoria: Off-road', 'Blindagem: 32 tiros', 'Slots do baú: 35', 'Peso máx. baú: 180 kg', 'Entrega: garagem'] },
    { model: 'menacer', nome: 'Menacer', brand: 'HVY', preco: 250, imageFolder: 'vehicles', descricao: 'Off-road blindado com torre de metralhadora. Resistência a 32 tiros.', beneficios: ['Blindado 32 tiros', 'Metralhadora torre', 'Entrega na garagem', 'Permanente'], dadosTecnicos: ['Modelo: menacer', 'Categoria: Off-road', 'Blindagem: 32 tiros', 'Slots do baú: 35', 'Peso máx. baú: 180 kg', 'Entrega: garagem'] },
    { model: 'barrage', nome: 'Barrage', brand: 'HVY', preco: 240, imageFolder: 'vehicles', descricao: 'Caminhão blindado com metralhadora dupla frontal. Resistência a 32 tiros.', beneficios: ['Blindado 32 tiros', 'Metralhadora dupla', 'Entrega na garagem', 'Permanente'], dadosTecnicos: ['Modelo: barrage', 'Categoria: Militar', 'Blindagem: 32 tiros', 'Slots do baú: 25', 'Peso máx. baú: 400 kg', 'Entrega: garagem'] },
    { model: 'technical3', nome: 'Technical Custom', brand: 'Karin', preco: 240, imageFolder: 'vehicles', descricao: 'Pick-up blindado com metralhadora. Resistência a 32 tiros.', beneficios: ['Blindado 32 tiros', 'Metralhadora', 'Entrega na garagem', 'Permanente'], dadosTecnicos: ['Modelo: technical3', 'Categoria: Off-road', 'Blindagem: 32 tiros', 'Slots do baú: 35', 'Peso máx. baú: 180 kg', 'Entrega: garagem'] }
];

/** Full Blindados – blindagem MÁXIMA / tanques (base: especial – Rhino, Khanjali, APC, etc.). productId: full_blindado_<model> */
window.FULL_BLINDADOS = [
    { model: 'rhino', nome: 'Rhino', brand: 'Militar', preco: 240, imageFolder: 'vehicles', descricao: 'Tanque clássico. Canhão principal. Blindagem total.', beneficios: ['Full blindado', 'Tanque', 'Canhão', 'Entrega na garagem', 'Permanente'], dadosTecnicos: ['Modelo: rhino', 'Blindagem: total', 'Canhão principal', 'Slots do baú: 25', 'Peso máx. baú: 400 kg', 'Entrega: garagem'] },
    { model: 'khanjali', nome: 'Khanjali', brand: 'TM-02', preco: 240, imageFolder: 'vehicles', descricao: 'Tanque moderno. Canhão, metralhadora e mísseis guiados. Blindagem total.', beneficios: ['Full blindado', 'Tanque', 'Canhão + mísseis', 'Entrega na garagem', 'Permanente'], dadosTecnicos: ['Modelo: khanjali', 'Blindagem: total', 'Canhão + mísseis', 'Slots do baú: 25', 'Peso máx. baú: 400 kg', 'Entrega: garagem'] },
    { model: 'apc', nome: 'APC', brand: 'HVY', preco: 260, imageFolder: 'vehicles', descricao: 'Tanque anfíbio blindado. Opera em terra e água; canhão e metralhadora.', beneficios: ['Full blindado', 'Anfíbio', 'Canhão + metralhadora', 'Entrega na garagem', 'Permanente'], dadosTecnicos: ['Modelo: apc', 'Blindagem: total', 'Anfíbio', 'Slots do baú: 25', 'Peso máx. baú: 400 kg', 'Entrega: garagem'] },
    { model: 'chernobog', nome: 'Chernobog', brand: 'HVY', preco: 280, imageFolder: 'vehicles', descricao: 'Lançador de mísseis guiados sobre chassis blindado. Até 30 mísseis.', beneficios: ['Full blindado', 'Lançador mísseis', 'Entrega na garagem', 'Permanente'], dadosTecnicos: ['Modelo: chernobog', 'Blindagem: total', 'Mísseis guiados', 'Slots do baú: 25', 'Peso máx. baú: 400 kg', 'Entrega: garagem'] },
    { model: 'halftrack', nome: 'Half-Track', brand: 'Bravado', preco: 250, imageFolder: 'vehicles', descricao: 'Meio-blindado militar com torre de metralhadora pesada. Blindagem total.', beneficios: ['Full blindado', 'Metralhadora torre', 'Entrega na garagem', 'Permanente'], dadosTecnicos: ['Modelo: halftrack', 'Blindagem: total', 'Metralhadora torre', 'Slots do baú: 25', 'Peso máx. baú: 400 kg', 'Entrega: garagem'] }
];

/**
 * Full Blindados Voadores – veículos que VOAM e são blindados/ataque (base: voadores + ficha – helicópteros de ataque, Conada Blindado).
 * productId: full_blindado_voador_<model>
 */
window.FULL_BLINDADOS_VOADORES = [
    { model: 'wrarmoredconada', nome: 'Conada Blindado', brand: 'Mantem', preco: 320, imageFolder: 'vehicles', descricao: 'Helicóptero blindado. Full blindagem e capacidade de voo.', beneficios: ['Full blindado', 'Voador', 'Entrega na garagem', 'Permanente'], dadosTecnicos: ['Modelo: wrarmoredconada', 'Blindagem: full', 'Tipo: helicóptero', 'Slots do baú: 25', 'Peso máx. baú: 35 kg', 'Entrega: garagem'] },
    { model: 'savage', nome: 'Savage', brand: 'Western', preco: 220, imageFolder: 'vehicles', descricao: 'Helicóptero de ataque. Canhão e mísseis. Blindado.', beneficios: ['Blindado', 'Voador', 'Canhão + mísseis', 'Entrega na garagem', 'Permanente'], dadosTecnicos: ['Modelo: savage', 'Categoria: helicopters', 'Tipo: heli', 'Slots do baú: 50', 'Peso máx. baú: 80 kg', 'Entrega: garagem'] },
    { model: 'hunter', nome: 'FH-1 Hunter', brand: 'Western', preco: 250, imageFolder: 'vehicles', descricao: 'Helicóptero de ataque. Alta resistência e armamento.', beneficios: ['Blindado', 'Voador', 'Entrega na garagem', 'Permanente'], dadosTecnicos: ['Modelo: hunter', 'Categoria: helicopters', 'Tipo: heli', 'Slots do baú: 50', 'Peso máx. baú: 80 kg', 'Entrega: garagem'] },
    { model: 'akula', nome: 'Akula', brand: 'Western', preco: 240, imageFolder: 'vehicles', descricao: 'Helicóptero de ataque furtivo. Blindado e armado.', beneficios: ['Blindado', 'Voador', 'Entrega na garagem', 'Permanente'], dadosTecnicos: ['Modelo: akula', 'Categoria: helicopters', 'Tipo: heli', 'Slots do baú: 50', 'Peso máx. baú: 80 kg', 'Entrega: garagem'] },
    { model: 'buzzard', nome: 'Buzzard Attack Chopper', brand: 'Nagasaki', preco: 220, imageFolder: 'vehicles', descricao: 'Helicóptero de ataque. Metralhadora e mísseis.', beneficios: ['Blindado', 'Voador', 'Entrega na garagem', 'Permanente'], dadosTecnicos: ['Modelo: buzzard', 'Categoria: helicopters', 'Tipo: heli', 'Slots do baú: 50', 'Peso máx. baú: 80 kg', 'Entrega: garagem'] },
    { model: 'valkyrie', nome: 'Valkyrie', brand: 'Western', preco: 230, imageFolder: 'vehicles', descricao: 'Helicóptero de ataque. Múltiplas metralhadoras.', beneficios: ['Blindado', 'Voador', 'Entrega na garagem', 'Permanente'], dadosTecnicos: ['Modelo: valkyrie', 'Categoria: helicopters', 'Tipo: heli', 'Slots do baú: 50', 'Peso máx. baú: 80 kg', 'Entrega: garagem'] },
    { model: 'annihilator', nome: 'Annihilator', brand: 'Western', preco: 210, imageFolder: 'vehicles', descricao: 'Helicóptero de ataque. Resistente e armado.', beneficios: ['Blindado', 'Voador', 'Entrega na garagem', 'Permanente'], dadosTecnicos: ['Modelo: annihilator', 'Categoria: helicopters', 'Tipo: heli', 'Slots do baú: 50', 'Peso máx. baú: 80 kg', 'Entrega: garagem'] }
];
